### DISCUSSION TITLE
Additional parameters

### DISCUSSION THREAD

**Discussion by christian-herber-nxp** [riscv-software-src/riscv-unified-db#136] [General]
I am missing a parameter to define the behavior upon decoding a reserved instruction. This is UNSPECIFIED in the isa manual.
Now, while most if not all implementations will trap on reserved instructions, it is legal to do something else (including implementing custom instructions).

Another parameter is the NMI mtval value. I am not sure if that is intentionally, as NMI is currently not in the unified-db it seems.

Finally, the cache block management has a number of UNSPECIFIED behaviors, that should be translated into parameters.

**Comment by james-ball-qualcomm** [comment]
This is exciting to see community members using riscv-unified-db.

Christian, are you able to make specific proposals to solve these issues? For example, creating proposals for parameter names, their allowed values, which extension(s) cause the parameter to be defined, and a few sentence description of the parameter?

What is the extension name for NMI? I assume you are referring to the restartable (or something like that) NMI extension. Whatever the name, it can definitely be added to the database by creating a YAML file.

**Comment by dhower-qc** [comment]
For reserved instructions, that would be captured by this parameter:

```yaml
    TRAP_ON_UNIMPLEMENTED_INSTRUCTION:
      description: |
        When true, fetching an unimplemented instruction will cause an `IllegalInstruction` exception.

        When false, fetching an unimplemented instruction is `unpredictable`.
      schema:
        type: boolean
```

For NMI, you are correct. That is not in the database yet.

Cache block management, the only parameter currently associated with it is the cache block size. Do you have a list of other parameters we need to add?
