### DISCUSSION TITLE
Scheme for specification prose

### DISCUSSION THREAD

**Discussion by dhower-qc** [riscv-software-src/riscv-unified-db#143] [General]
We've tried two methods to conditionally apply asciidoc source depending on parameters or equations.

First, we tried using ERB. It works fine but requires some basic knowledge of Ruby.

Second, we tried using a [when,"condition"] Asciidoc style. It works for asciidoctor.js because I made a plugin, but doesn't work with asciidoctor(-pdf) because there is no plugin there yet.

I'm not sold on either approach. More discussion is needed.

**Comment by dhower-qc** [comment]
@edolnx, @kersten1

Stepping up a level, there are several things we want to identify _about each statement in the prose_.

* The **type** of statement (normative, non-normative)
* Any **conditions** that apply for the statement
* A _unique_ **identifier** for the statement that can be referenced throughout the database (e.g., for test plans, executable spec, etc.)

Given that, here is a strawman for how we might represent prose in the database:

For the prose:

> The `mimpid` CSR provides a unique encoding of the version of the processor implementation. This register must be readable in any implementation, but a value of 0 can be returned to indicate that the field is not implemented. The Implementation value should reflect the design of the RISC-V processor itself and not any surrounding system.
>
> The `mimpid` CSR is MXLEN bits long.
>
> [NOTE] The format of this field is left to the provider of the architecture source code, but will often be printed by standard tools as a hexadecimal string without any leading or trailing zeros, so the Implementation value can be left-justified (i.e., filled in from most-significant nibble down) with subfields aligned on nibble boundaries to ease human readability.


```yaml
description:
- type: spec # short for normative
  text: |
    The `mimpid` CSR provides a unique encoding of the version of the processor implementation.
  id: misa-01
- type: spec
  text: |
    This register must be readable in any implementation,
    but a value of 0 can be returned to indicate that the field is not implemented.
  misa-02
- type: spec
  text: |
    The Implementation value should reflect the design of the RISC-V processor itself
    and not any surrounding system.
  id: misa-03
- type: spec
  text: |
    The `mimpid` CSR is MXLEN (32) bits long.
  cond: XLEN == 32
  id: misa-04
- type: spec
  text: |
    The `mimpid` CSR is MXLEN (64) bits long.
  cond: XLEN == 64
  id: misa-05
- type: info # short for non-normative
  text: |
    The format of this field is left to the provider of the architecture source code,
    but will often be printed by standard tools as a hexadecimal string without any leading
    or trailing zeros, so the Implementation value can be left-justified (i.e., filled in from
    most-significant nibble down) with subfields aligned on nibble boundaries to ease human
    readability.
  id: misa-06
```

Things I like:

- Can generate config-specific docs from this data
- Can build robust testplans & implementations from this data

Things I don't like:

- Pretty verbose

Note that we can probably come up with a way to generate the ids so you would never have to hand-type those.

Thoughts?
