### ISSUE TITLE
Additional parameter for mtvec

### ISSUE THREAD

**Issue by christian-herber-nxp** [riscv-software-src/riscv-unified-db#127]
According to the ISA manual, 

> the mtvec register must always be implemented, but can contain a read-only value

There is currently no parameter to allow mtvec.base to be read-only.
Thus, I would like to suggest adding:

```
    MTVEC_BASE_READ_ONLY:
      description: |
        Whether or not the `mtvec.base` field is read only or not.

        Possible values:

        true::
          The `mtvec.base` field is read-only.
        
        false::
          The `mtvec.base` field is read/write.
      schema:
        type: boolean
```

**Comment by james-ball-qualcomm** [comment]
I had the same impression until Derek showed me something (see screenshot). The db currently assumes that if you only support one value for mtvec.base, then it is read-only. Seems like a reasonable assumption. If you agree, maybe we should just update the description to say this so that others don't get caught by this.

![image](https://github.com/user-attachments/assets/8b49f849-210d-4efc-989a-a7236a677939)

**Comment by dhower-qc** [comment]
@james-ball-qualcomm, that's for mtvec.MODES. @christian-herber-nxp is referening to mtvec.BASE

**Comment by dhower-qc** [comment]
Unfortunately, I think the allowed values are more complicated that just read-only-0 or anything since the field is WARL.

How about this?

```yaml
    MTVEC_BASE_VALUES:
      description: |
        The supported values in `mtvec.base`. 

        Possible values:

        none::
          `mtvec.base` is read-only-zero.

        width::
          `mtvec.base` supports any value that fits in MTVEC_BASE_WIDTH bits

        custom::
          `mtvec.base` supports a custom set of values. Any attempt to read or write `mtvec.BASE` will
          result in UNPREDICTABLE execution.
      schema:
        type: string
        enum: [none, width, custom]
    MTVEC_BASE_WIDTH:
      description: |
        When MTVEC_BASE_VALUES is 'width', the bit width of supported value in `mtvec.BASE`
      schema:
        type: integer
        minimum: 1
        maximum: 60
      extra_validation: |
        # max width is actually 30 for RV32
        assert MTVEC_BASE_WIDTH <= 30 if MTVEC_BASE_VALUES == "width" && XLEN == 32
```
