### ISSUE TITLE
PseudoInstructions defined by other extensions

### ISSUE THREAD

**Issue by AFOliveira** [riscv-software-src/riscv-unified-db#131]
How should we organize the following?

`$pseudo_op rv_zicsr::csrrs  frcsr      rd 19..15=0 31..20=0x003 14..12=2 6..2=0x1C 1..0=3
`

To those unware of the format, this means pseudoinstruction **frcsr** is a defined by instruction **csrrs** which belongs to extension **zicsr**.

Should this still only be defined in the zicsr folder? Should this have another parameter like:
```
pseudoinstructions:
  - when: (csr == 0x3) && (rs1 == 0x0)
    to: frcsr
   **ext: F**

```
