### ISSUE TITLE
assembly syntax

### ISSUE THREAD

**Issue by drom** [riscv-software-src/riscv-unified-db#208]
I am looking at `assembly` field for instruction and wondering. Should it be in the order/syntax/optionallity of actual assembly language?

Here is an example from here https://github.com/riscv-software-src/riscv-unified-db/blob/main/arch/inst/V/vfadd.vf.yaml#L8

```yaml
vfadd.vf:
  long_name: No synopsis available.
  description: |
      No description available.
  definedBy: V
  assembly: vm, vs2, xs1, vd
  ...
```

An actual assembly order is:

```asm
vfadd.vf   vd, xs1, vs2[, vm]

vm - is optional
```

or:

```yaml
vlse8.v:
  long_name: No synopsis available.
  description: |
      No description available.
  definedBy: V
  assembly: nf, vm, xs2, xs1, vd
  ...
```

in assembly:

```asm
vlse8.v  vd, (xs1), xs2[, vm][, nf]
```

or:

```yaml
bne:
  long_name: Branch if not equal
  description: |
    Branch to PC + imm if
    the value in register rs1 is not equal to the value in register rs2.

    Raise a `MisalignedAddress` exception if PC + imm is misaligned.
  definedBy: I
  assembly: xs1, xs2, imm
   ...
```

```asm
bne  xs1, xs2, <pc + imm>
```

We clearly need a better way to express these details.
