### ISSUE TITLE
Remove extension version numbers from certificate_model YAML files since they specify the version of the related standards

### ISSUE THREAD

**Issue by james-ball-qualcomm** [riscv-software-src/riscv-unified-db#325]
```
# Specification versions
tsc_profile: null # None for MC100
unpriv_isa_manual_revision: "20191213"
priv_isa_manual_revision: "20190608-Priv-MSU-Ratified"
debug_manual_revision: "0.13.2"

# XXX - Remove version information since specifying priv/unpriv ISA manual should imply this.
extensions:
  I:
    version: "~> 2.1"
    presence: mandatory
  C:
    version: "~> 2.2"
    presence: mandatory
```
