### ISSUE TITLE
AnyOf vs AllOf

### ISSUE THREAD

**Issue by AFOliveira** [riscv-software-src/riscv-unified-db#362]
**Describe the bug**
Some instructions have AnyOf and AllOf wrongly assigned. I'm trying to catch them all and submit a PR soon.
@BrianAnakPintar can you please address some examples of that?

**Comment by BrianAnakPintar** [comment]
Examples:
### froundnx.h
UDB
```yaml
kind: instruction
name: froundnx.h
long_name: No synopsis available.
description: |
  No description available.
definedBy:
  anyOf: [Zfa, Zfh]
```
riscv-opcodes
```json
"froundnx_h": {
    "encoding": "010001000101-------------1010011",
    "variable_fields": [
        "rd",
        "rm",
        "rs1"
    ],
    "extension": [
        "rv_zfh_zfa"
    ],
```

### froundnx.q
UDB
```yaml
name: froundnx.h
long_name: No synopsis available.
description: |
  No description available.
definedBy:
  anyOf: [Zfa, Zfh]
```
riscv-opcodes
```json
"froundnx_q": {
    "encoding": "010001100101-------------1010011",
    "variable_fields": [
        "rd",
        "rm",
        "rs1"
    ],
    "extension": [
        "rv_q_zfa"
    ],
    "match": "0x46500053",
    "mask": "0xfff0007f"
},
```
### fmvp.q.x
UDB
```yaml
name: fmvp.q.x
long_name: No synopsis available.
description: |
  No description available.
definedBy:
  anyOf: [Q, Zfa]
```
riscv-opcodes
```json
 "fmvp_q_x": {
    "encoding": "1011011----------000-----1010011",
    "variable_fields": [
        "rd",
        "rs1",
        "rs2"
    ],
    "extension": [
        "rv64_q_zfa"
    ],
    "match": "0xb6000053",
    "mask": "0xfe00707f"
    },
```

Others include: 
`fround.q`, `fmvp.d.x` and more.
