### ISSUE TITLE
Missing base on some instructions

### ISSUE THREAD

**Issue by BrianAnakPintar** [riscv-software-src/riscv-unified-db#363]
**Current value and location**
Instructions such as `sc_d`, `remuw`, `remw`, `mulw`, `divuw` are missing `base:64` for 64

Here's some example to showcase what I meant:

UDB
```json
"sc_d": {
  "encoding": "00011------------011-----0101111",
  "variable_fields": [
      "aq",
      "rd",
      "rl",
      "rs1",
      "rs2"
  ],
  "extension": [
      "rv_a",
      "rv_zalrsc"
  ],
  "match": "0x1800302f",
  "mask": "0xf800707f"
  },

"remuw": {
  "encoding": "0000001----------111-----0111011",
  "variable_fields": [
      "rd",
      "rs1",
      "rs2"
  ],
  "extension": [
      "rv_m"
  ],
  "match": "0x200703b",
  "mask": "0xfe00707f"
  },
```
riscv-opcodes
```json
"sc_d": {
  "encoding": "00011------------011-----0101111",
  "variable_fields": [
      "aq",
      "rd",
      "rl",
      "rs1",
      "rs2"
  ],
  "extension": [
      "rv64_a"
  ],
  "match": "0x1800302f",
  "mask": "0xf800707f"
  },

"remuw": {
    "encoding": "0000001----------111-----0111011",
    "variable_fields": [
        "rd",
        "rs1",
        "rs2"
    ],
    "extension": [
        "rv64_m"
    ],
    "match": "0x200703b",
    "mask": "0xfe00707f"
},
```

**Comment by AFOliveira** [comment]
If you check https://github.com/riscv-software-src/riscv-unified-db/pull/376 that should be solved. Please note that some bases are defined as RV64 and RV32 in the case of the instruction encoding differing from one to the other, i.e. bclri
 
```
 encoding:
  RV32:
    match: 0100100----------001-----0010011
    variables:
      - name: shamt
        location: 24-20
      - name: rs1
        location: 19-15
      - name: rd
        location: 11-7
  RV64:
    match: 010010-----------001-----0010011
    variables:
      - name: shamt
        location: 25-20
      - name: rs1
        location: 19-15
      - name: rd
        location: 11-7

```
