### ISSUE TITLE
RISC-V Opcodes vs UDB gaps

### ISSUE THREAD

**Issue by AFOliveira** [riscv-software-src/riscv-unified-db#478]
RORW has the following variables in UDB:

```
  variables:
    - name: shamt
      location: 24-20
    - name: rs1
      location: 19-15
    - name: rd
      location: 11-7
```

However, the ISA is states that it's rs2 and not shamt. 

![Image](https://github.com/user-attachments/assets/58970a19-d9cb-411a-ad42-14aa01121492)

Aparently, sail code has shamt variable, but fetches it from rs2:
```
sail(): |
  {
    let rs1_val = (X(rs1))[31..0];
    let shamt = (X(rs2))[4..0];
    let result : bits(32) = match op {
      RISCV_ROLW => rs1_val <<< shamt,
      RISCV_RORW => rs1_val >>> shamt
    };
    X(rd) = sign_extend(result);
    RETIRE_SUCCESS
  }

```

I did not PR the change because it also requires IDL code and likely there are a lot of people who may change that with way less effort than me.
