### ISSUE TITLE
`NUM_EXTERNAL_GUEST_INTERRUPTS` (`GEILEN`) maximum for RV32 is 31

### ISSUE THREAD

**Issue by ThinkOpenly** [riscv-software-src/riscv-unified-db#619]
**Current value and location**
"arch/ext/H.yaml":
```
  NUM_EXTERNAL_GUEST_INTERRUPTS:
    description: |
      Number of supported virtualized guest interrupts

      Corresponds to the `GEILEN` parameter in the RVI specs
    schema:
      type: integer
      minimum: 1 
      maximum: 63
```

**Expected value**
What do you think the value(s) should be?
Priv spec, 18.2.4:
> For any one physical hart, the maximum number of virtual harts that may directly receive guest external interrupts is limited by GEILEN. The maximum this number can be for any implementation is 31 for RV32 and 63 for RV64, per physical hart.

So, the maximum value for NUM_EXTERNAL_GUEST_INTERRUPTS (a.k.a. GEILEN) is 63 for RV64 and 31 for RV32.

I presume "extra_validation" is required for "NUM_EXTERNAL_GUEST_INTERRUPTS". Something like below?
```
assert NUM_EXTERNAL_GUEST_INTERRUPTS < 32 if SXLEN == 32
```
