### ISSUE TITLE
Differentiate between arguments

### ISSUE THREAD

**Issue by AFOliveira** [riscv-software-src/riscv-unified-db#648]
In instructions, there are variables that are assembly defined - like the normal regs - rs1,rs2,rd - and other variables that actually cause a different instructions - i.e. aq, rl. We need to differentiate them in order to generate all valid instructions out of UDB.

### Example 

amoadd.b.yaml:
```
name: amoadd.b
long_name: No synopsis available.
description: |
  No description available.
definedBy: Zabha
assembly: xd, xs2, xs1
encoding:
  match: 00000------------000-----0101111
  variables:
    - name: aq
      location: 26-26
    - name: rl
      location: 25-25
    - name: rs2
      location: 24-20
    - name: rs1
      location: 19-15
    - name: rd
      location: 11-7
```

This will have an `assembly: xd,xs1,xs2`, but it should turn into 4 instructions:

-  amoadd.b
- amoadd.b.aq
- amoadd.b.rl
- amoadd.b.aq.rl
