### ISSUE TITLE
Add "recommended" values for extension parameters

### ISSUE THREAD

**Issue by ThinkOpenly** [riscv-software-src/riscv-unified-db#704]
**Is your feature request related to a problem? Please describe.**
Currently, extension parameters are defined with types and possible values ("Sdtrig" extension, Machine Context (`mcontext`), "hcontext" field; from PR #524):
```
params:
  DBG_HCONTEXT_WIDTH:
    schema:
      type: integer
      minimum: 0
      maximum: 14
    description: Specifies the size of HCONTEXT
```
Some parameters have "recommended" values in the spec, for example (Machine Context, `mcontext`, "hcontext" field):
> An implementation may tie any number of upper bits in this field to 0. If the H extension is not implemented, it’s recommended to implement 6 bits on RV32 and 13 bits on RV64 (as visible through the mcontext register). If the H extension is implemented, it’s recommended to implement 7 bits on RV32 and 14 bits on RV64.

**Describe the solution you'd like**
Some means of expressing a recommended value for each type (integer, boolean, etc.), including with the conditional logic required by the example above, seems desirable to allow configurations to not have to determine the recommended values and explicitly set all of the configuration parameters to those values.
